/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 19.09.2026 17:47:42

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1504;
#else
constexpr int kTensorArenaSize = 480;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,135 } };
const TfArray<1, float> quant0_scale = { 1, { 3.9357876777648926, } };
const TfArray<1, int> quant0_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data1[3] = { 1, 1, -1, };
const TfArray<1, int> tensor_dimension1 = { 1, { 3 } };
const TfArray<1, float> quant1_scale = { 1, { 0.014564367011189461, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[3*10] = { 
  75, 15, 109, -98, -45, 57, 92, -99, -126, 92, 
  71, 74, -24, -80, -118, 13, 39, -100, 14, -25, 
  -104, -23, 127, -2, -110, -98, -106, -59, 117, 33, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 3,10 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0052310219034552574, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[10] = { 0, 0, 0, -1, 0, 1, 1, -1, 0, 0, };
const TfArray<1, int> tensor_dimension3 = { 1, { 10 } };
const TfArray<1, float> quant3_scale = { 1, { 0.018813937902450562, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[10*20] = { 
  45, -86, -75, 14, 111, 17, 126, -117, -6, -57, 26, 21, 71, 127, 60, -92, 0, -29, -79, 27, 
  -63, -127, 76, 75, 60, -46, -58, -108, -103, 20, -58, -59, 70, 25, 78, 100, -56, 38, -49, -34, 
  -25, -108, -3, 117, -54, -66, -40, 23, -46, -13, 36, 56, -24, -96, -15, -78, 94, -108, -111, -90, 
  65, 12, 102, 1, -74, 82, -65, -54, -35, 82, 109, 53, -82, -105, -6, -54, -32, -60, 116, 94, 
  -50, 69, -105, -45, -94, 80, -40, 32, -100, 68, 102, 64, -22, 55, 29, -102, -53, 112, 82, 64, 
  -98, 81, -75, 59, -34, -127, -7, 89, -126, -52, 88, 67, -57, 70, -25, -72, -39, 69, -74, 5, 
  102, 55, -63, -85, 89, 91, 13, -35, -26, 3, 71, 46, -80, -46, 12, -16, 69, -20, -17, -39, 
  -17, 98, 49, 66, -13, 93, 97, -126, 124, -33, -67, 125, 74, -30, -113, 52, 93, 6, 14, 94, 
  70, 43, 59, 43, 97, 34, -121, -31, -36, 14, 104, 23, -5, -117, -40, 103, -99, 79, -54, -36, 
  49, -80, -18, -2, 89, 112, -22, 12, 86, -104, -67, 54, -83, -60, 62, -21, -21, 99, 3, 86, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 10,20 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0034372161608189344, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[20] = { 0, 1, -1, -1, 0, -2, 0, 1, -1, 0, 1, 1, 0, 0, 1, -1, 1, 0, -1, 0, };
const TfArray<1, int> tensor_dimension5 = { 1, { 20 } };
const TfArray<1, float> quant5_scale = { 1, { 0.0064443619921803474, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[20*135] = { 
  0, -17, -26, 98, 34, 58, 34, -76, 39, -95, -4, 42, -105, -77, -26, 104, 29, 86, -57, -57, 102, -31, 98, 21, -109, 75, -58, -58, -82, -106, 28, 36, 71, -98, -111, 51, -74, 85, -11, -77, 53, -10, -89, -36, -103, 97, -42, 103, -77, -85, -21, -110, 47, -26, -100, 75, 112, 88, 117, 69, 45, -48, 12, -84, -18, -83, 2, 38, 100, -15, 28, -101, -73, -31, -25, -65, 82, 55, -16, 97, 33, -4, -20, 36, -24, 14, -120, -14, -90, -111, 41, -28, -60, 99, -13, -113, 112, 62, -89, -46, -8, -119, 23, 60, -32, -49, -46, 4, -65, -57, 93, 33, 4, 75, -60, 108, -54, 40, -118, 37, 54, 2, 25, 109, -118, -21, 74, 6, 94, -18, -103, -69, 109, 33, 95, 
  -117, -14, 91, 6, -30, 26, 42, 41, 58, 108, -82, 44, 7, 26, 78, -59, 97, 64, 119, -77, -26, -20, 102, -17, 65, 63, -16, 85, -34, -93, -27, 115, 108, 119, 86, -32, -95, -17, 25, -62, -45, -59, 120, 88, 74, -32, 82, -88, 1, 5, -102, -9, 10, -39, -17, -126, -118, 85, 103, -89, -16, 87, -42, -21, -35, -5, 80, -113, 71, -27, 112, -62, 70, -13, 11, 88, -32, -61, -3, 111, -10, -120, -66, -7, 45, 14, -18, -82, 28, -23, 36, 31, 100, 19, 11, 73, -51, -92, 25, -106, 20, 107, -10, -12, -76, 60, 92, -70, -23, -27, -40, -113, 122, 41, -29, 109, 36, 23, -94, -89, 21, -106, -32, -57, 60, -5, -4, 40, -104, 102, -37, -28, 79, -31, 117, 
  77, -10, -96, -75, 46, -69, 67, 94, 107, -10, -84, 25, -78, 52, -75, 77, 33, 64, 2, 56, 123, -102, 60, -99, 9, -36, 107, 59, -56, -87, -51, 73, 54, -91, -28, -45, -101, -2, 74, -82, 55, 55, -116, -25, 36, -22, -56, -90, 51, -36, 55, -32, -27, -8, 63, -92, 18, 25, 8, -39, 103, -47, -25, 20, -27, 74, 33, -72, -42, -45, -12, -122, 9, 106, -15, -93, -106, 58, -64, -77, 43, -64, 48, 1, 19, 15, -36, -7, -99, -6, -83, 104, 32, -33, 113, 75, 32, 54, 35, 35, -109, -96, -52, -89, 48, -52, 99, 78, 11, -15, -51, 70, 4, -101, -79, -104, 50, 120, -21, 56, -52, 91, 113, -120, 98, 93, 32, 84, -94, 2, 61, -79, 17, 53, 53, 
  -98, 67, -58, 79, -15, 63, -17, 109, 53, -100, 102, 100, 66, 68, 45, -32, -96, -64, 40, 80, -72, 57, -82, -51, 66, 54, -91, 71, 104, 82, -44, 44, 93, -58, 66, 9, 116, -109, 28, 90, -103, 66, -4, 86, 107, -91, 0, -70, 79, 49, -84, -9, -29, -126, 28, -86, -96, -108, -53, -20, 101, 35, 106, 85, -74, -102, 76, -108, -81, -114, 62, -68, -64, -80, 31, 49, -35, 113, 37, 109, 17, 77, 87, -31, -14, -101, -17, -51, 66, -54, 48, 45, -92, 23, 93, -52, -76, -30, 87, -28, -33, -5, 104, -74, -63, -12, 8, -38, 21, 38, -94, 27, -9, 80, 2, 101, -113, 5, 88, -1, -102, 90, -2, 32, -105, -1, -1, -66, 34, 46, -50, -113, -36, 98, -29, 
  97, 24, 19, -75, -94, -89, 99, -29, -56, 70, -35, 22, -75, -53, -82, 64, 69, 78, -10, -28, -13, 109, -24, -19, -38, 5, 86, 80, -109, -95, 54, -77, 105, -86, -38, -59, -37, -110, 25, 68, 12, 35, -104, -43, 66, -74, 87, 71, -23, 80, 75, 86, -92, -31, -33, 114, 75, 91, 103, 69, -102, -96, 108, 109, 6, 66, -51, 117, -117, -29, -103, 31, 82, 41, 49, 55, -39, -33, -58, -47, 88, -114, 59, -84, 39, -68, 25, -85, 79, -43, -45, 4, 29, 77, 34, 3, 22, -26, -88, -93, -26, -105, 27, -35, 107, -62, -113, -29, -80, 38, -77, -6, -71, -5, 44, -11, -46, -81, -64, -15, 106, -33, -69, -15, -102, 7, 111, -92, -55, 48, -38, -21, 47, -21, -27, 
  -36, 95, 27, 5, -46, -100, 6, 112, -52, 26, -105, -37, -107, 49, 14, -8, -113, 28, -37, 16, -87, -88, -17, -66, 81, -37, 26, -17, -50, 123, -13, -18, 86, -78, 21, -117, 81, -63, 54, 114, 76, 39, -87, -38, 14, -117, -83, -73, 6, 70, 98, -23, 33, -55, 52, 77, 46, -5, 61, 2, 25, -119, 72, -94, -27, 5, -33, 89, 96, 48, 105, -60, 81, -81, -112, -67, -20, -25, 70, -6, -99, 44, -53, 100, 0, -97, 28, -13, 111, -27, 14, 14, -67, 102, -1, -17, -20, 32, -8, 72, -10, 42, 106, -74, 20, 14, 110, -85, 40, 71, -6, 0, 30, 62, 78, 16, 52, -92, 38, -68, -108, 60, -98, 12, -1, 104, -20, -39, -52, -97, 3, 33, -81, -48, 17, 
  58, -34, -42, -65, -74, -116, -39, 85, -42, 10, -5, -9, 1, 69, 47, -19, -48, -60, 117, 92, -56, 23, -53, 77, -47, -12, 119, -98, 96, 30, 80, -110, 1, -15, -93, 69, -108, 49, -96, 119, -13, 26, -9, 6, -59, -102, 115, -64, -12, -25, -78, 98, -103, 73, 38, -13, 10, 99, 65, -43, -74, 12, 85, -72, 57, 31, -107, 75, -88, -65, 20, 105, -35, 55, 35, 71, 56, 94, 52, -52, 89, 73, 6, 35, -68, -34, 73, 30, -55, -51, -85, 74, -47, 109, -38, -114, -56, -72, -106, -11, -71, -68, 5, -33, 114, -19, -17, -80, -64, -6, -6, 64, 78, -118, 29, -26, 66, -47, -100, -41, -63, 25, -98, 1, -44, -96, -11, 52, -33, -100, 51, -112, -11, 57, 80, 
  87, -123, 28, 92, 108, 40, 38, 54, -32, 99, -32, 108, -51, 51, -72, -109, -34, -58, -81, 105, 92, -86, -59, 3, -22, 119, -27, 31, -119, -24, 17, 115, 31, -99, -38, -105, -22, 26, 75, -50, -16, 39, 125, 120, 47, -12, 18, -107, -80, 63, -76, -27, -17, 24, -38, -81, -109, 73, 83, -111, -75, -33, 66, -87, 57, 27, 19, -44, -49, 124, -67, 26, -23, 42, -8, 12, -39, 74, -57, 63, 124, -119, 64, -11, 21, -108, 56, 57, 85, -36, -31, -108, 10, -77, -92, -46, -35, -97, 11, 108, -44, 64, -15, -100, -10, -36, -48, -98, 110, -49, -74, -106, 25, 60, 106, -44, 95, -21, -52, 40, -48, 37, -6, -95, 51, 50, -81, -104, -29, -29, 74, -2, -21, 25, -74, 
  65, 120, 77, -11, -107, 67, -19, -76, -16, -19, 14, 78, 78, -49, 13, -56, 43, -61, 118, 30, 115, 90, 101, 42, 68, 70, 79, -11, 104, -98, 75, -118, -24, -7, -104, -40, -104, 106, -73, 20, -65, -68, -113, -52, -110, 35, -36, -9, -53, 30, -116, -122, 112, -81, 61, 62, 22, 65, -17, -51, 70, -33, 95, -47, 12, -108, 111, 80, 67, -66, -56, -42, 20, -90, -31, -98, -92, -60, -72, 95, -65, -68, -87, -49, 109, 20, -12, 37, 62, 59, 0, -102, -102, -18, 85, -15, 103, 23, 47, -66, -77, -66, -45, 48, 7, 80, -36, 8, 31, -6, -48, 88, 16, 48, 88, 104, 33, -74, 104, -25, 92, 89, 0, -41, 56, -116, 22, 122, -101, 99, -113, 87, -125, -40, -89, 
  -100, 53, -101, -8, -69, 71, -109, -1, -65, -120, -102, -82, -120, -31, -76, 93, -13, 70, 84, -76, -25, 75, 23, 111, 120, 80, 6, 35, -3, 54, -52, -34, -87, -4, 84, 36, 81, 90, -17, 17, 27, 50, -65, 29, -51, -119, 77, 49, 102, -93, 61, 113, -115, -112, -71, 22, 67, 13, -108, 36, -106, -65, -83, 90, 1, -28, -112, -34, -82, 50, -75, 79, 103, 3, -21, -90, 110, -34, -119, 82, 60, 115, -101, -67, -85, 91, -82, -64, 57, 22, 94, 46, -33, -15, 14, 108, -3, -111, -92, -53, 74, -92, -103, -43, 17, -6, -120, -54, 48, 44, 56, -65, -50, -53, 101, 78, 94, 66, 80, 59, 94, -116, -58, 102, -66, 54, 85, -39, -60, 47, -55, -69, -44, -34, -101, 
  113, 20, 46, -125, -90, -45, 71, 23, -4, 38, -98, 28, 21, -89, 60, -68, 1, 2, 40, 18, -109, 45, -105, 96, 100, -18, -53, -40, 77, 73, -125, -90, -91, -25, 122, 108, -36, -101, -101, 22, 49, -12, 7, -34, -35, 81, 1, -121, 59, 50, -34, -73, -20, -4, 83, 97, -86, -62, 30, -16, 32, 44, 80, 78, 22, -124, -118, 57, 57, 34, 96, 17, -29, -56, -9, 95, 36, -72, 55, 121, -47, -84, 28, -88, -62, 84, -39, 32, -42, -57, -5, 103, 47, -74, -14, 10, -65, 45, -103, 54, 92, 65, 44, 53, 61, -54, 6, -104, 88, 1, -37, -7, 44, 60, -113, 19, -32, 99, -52, -77, -70, -96, -69, -88, 102, 59, -89, 18, 48, -118, 80, -47, -90, -109, 40, 
  -17, 36, 101, -43, -88, -101, 123, -42, 93, -29, 98, 105, 69, 112, -39, 59, -45, -37, 106, -1, -31, -32, 118, 10, 41, 52, 80, 57, 116, 41, -17, -21, 10, -44, 37, -22, -84, 25, 26, 57, 56, 91, 108, -14, -58, -38, 22, 51, -110, -7, -84, 85, 41, 45, 108, 64, 55, -28, 17, -90, 95, 68, 2, -34, 80, 67, 71, -26, -19, -23, -87, 9, -68, -76, 91, 26, 56, 101, 56, 25, 59, 107, -104, -68, -118, -103, -72, 60, -10, 82, 58, -98, -121, -96, 26, 40, 57, 83, -15, -33, -19, -12, 83, 87, 79, 50, 16, 122, -2, -105, -30, 18, 52, 42, -103, -73, -105, 8, 70, 37, 111, 110, 13, -19, -4, -27, -64, -94, 114, 81, -69, 76, 54, -19, -99, 
  -55, -114, 1, -38, 72, -103, -71, -116, -96, 57, -28, -110, 29, 63, -41, 88, 15, -40, 99, -32, 56, 67, -75, 74, 60, -38, 8, -57, 100, -31, -51, 28, -115, 107, 74, 74, 96, -78, -101, -74, -14, 18, -96, -58, -119, -47, 110, 67, -18, 119, 79, -105, -119, 22, -78, -117, -81, 36, -23, 52, -39, -86, -91, 79, 19, 29, 79, 45, 10, 81, -1, -56, 54, 77, 33, -118, -47, 91, -103, -103, 19, 51, 101, 76, 111, 90, -109, -69, 5, 72, -85, 107, 24, 20, -82, -108, 43, 12, 77, -27, -81, 70, 57, 38, -3, -99, -8, 95, 60, 18, -6, -40, 4, -59, -80, 18, -58, -39, 105, 62, 67, -12, 41, -64, 39, 48, -119, 65, -65, 100, -8, 63, 96, -8, 36, 
  28, -120, -65, -7, 106, 115, -101, 111, -16, 28, 23, 31, 105, 32, -23, -85, -120, -19, -97, -44, -91, -94, -6, -39, -51, -119, -80, 102, -20, 9, 36, -116, -89, -115, -17, 29, 54, -9, 96, -37, 110, 58, 98, -86, 100, -59, -6, 67, 119, 72, 39, 55, -88, -57, 108, -47, 20, 82, 60, -21, 1, -41, -20, -92, 78, 92, 96, 94, 23, 113, -99, -23, 75, -23, 56, -87, -64, -55, 56, -69, -48, 53, -35, -41, 65, 18, 86, 101, -6, -117, 8, 25, -81, 64, -114, -86, -52, 112, 1, -60, 21, 104, 29, -88, -73, 51, 1, -12, -33, 50, 75, -108, -72, 35, -78, 63, 65, -68, 68, -104, -4, -45, -54, -39, 107, 21, -95, 92, 43, 101, -98, -93, 32, -4, -99, 
  108, -106, -70, 15, 13, -65, -48, 46, 62, 39, 109, -124, -111, 120, -111, -41, -100, 21, 66, -100, 95, 107, -56, 92, -107, -65, -12, -99, 88, -39, 111, -60, -49, 78, -13, -73, -96, 22, 89, -119, -114, 103, -109, 82, -13, 72, -50, -82, -124, -46, -18, 58, 44, -15, -91, -83, 101, -37, 108, -62, 12, 55, -66, 107, 11, 101, 94, 79, -15, 68, 17, -67, 106, -54, 97, 48, -46, 36, 1, 15, 69, 12, -86, -61, 13, -90, 95, 15, -93, 29, -55, 31, -24, 58, -97, 3, 97, 98, 101, 120, -116, 104, -86, 92, -93, -37, 79, -100, -48, -75, -59, -12, 119, 69, -104, 77, 122, -102, 84, 92, -70, -12, -7, -66, -78, -88, -9, 107, 103, -88, -36, -66, 0, 2, 86, 
  0, 105, -84, -104, -116, 26, -20, 14, 37, 40, -2, 51, -59, 51, 50, 87, 14, 47, 42, 75, -104, 108, -102, 46, 22, -5, -59, -43, -18, -61, 39, -46, -49, 57, -15, 19, 0, -105, 35, 113, 64, -63, 30, -91, 78, -73, -102, -25, -79, 77, 43, -15, 78, 95, 48, -63, 109, 60, -92, 93, -2, -80, 16, -51, 24, 54, 26, -76, 4, 71, -108, 91, 96, 108, 54, 93, -55, 21, 95, 39, -89, -70, 21, 117, 127, 86, 5, 56, 62, 113, -3, 122, 29, 83, 109, 78, -104, 53, 57, 55, 95, 108, 121, -41, 75, -80, 12, 41, 118, -63, 41, -93, -121, 15, 64, -81, -46, -104, 1, -8, -56, 19, -22, -48, 39, -34, -69, -51, -29, -81, -27, -42, 19, 95, -85, 
  1, -82, -53, -17, 102, -22, -35, -81, 49, -106, -110, -43, 19, 63, -35, 49, -88, -53, 51, -44, -106, -77, 50, -45, 55, -34, -15, 91, -89, 80, 35, 4, 99, -66, -30, -57, 35, -108, -59, -4, 5, -14, 26, 92, -7, -96, 87, -115, -18, -42, 15, -10, -16, -82, -17, -119, -23, -33, 82, -77, -72, 108, -63, 7, -89, 49, -7, -40, 4, 118, -93, -18, -62, 97, 84, 54, -51, 38, -66, 29, 32, 106, -125, -44, -16, 85, 12, -68, 118, -23, 14, 110, 105, 11, 24, -51, 16, -31, 111, -56, -23, -21, -29, -11, 111, 90, 62, 118, -21, -75, 61, 21, 88, -105, -103, 46, -28, 105, -74, -107, 50, -12, -66, -8, 117, 29, -13, -111, 102, 97, -17, 102, -13, 32, -76, 
  -26, 52, 99, 75, 87, -36, -46, 100, 42, -19, -49, 109, -51, 85, -84, -39, -82, 32, 106, -72, 57, -59, -88, 119, -64, -92, -59, 35, -15, -76, -24, -90, 5, 30, 12, 119, 110, -71, 77, -109, -113, -33, 120, -35, 37, -82, 4, 107, -99, 58, -54, -68, 111, 64, 31, -95, 82, -113, -26, -55, 37, -92, 59, 108, -31, 56, -22, 3, 40, -33, 92, -42, 72, 102, 49, 20, -96, -87, 88, -91, -95, -113, -112, 14, 53, 111, -45, 28, 27, 54, -6, 108, -117, -69, 86, 64, 51, -41, 108, -113, 96, 41, 0, -72, -67, -119, -95, 113, 28, -125, -115, -64, 92, 6, -81, 36, 84, 113, -66, -24, -81, 109, 32, 106, 3, 52, 51, 94, 105, 95, 62, 53, -72, 94, 10, 
  -104, -34, 60, -120, 54, 7, -81, -15, -7, -45, -114, -49, -105, -88, -93, -66, 4, -74, -69, 42, -63, 96, -68, 90, -55, -107, -8, -37, -110, -86, 52, -55, -79, -111, 114, 91, 30, -84, -95, -43, -90, 21, -75, 58, 0, -22, 117, 24, -98, -113, 3, -105, 50, -72, 72, -88, -81, -78, -36, 82, -41, -66, -82, 90, 56, -66, 101, -100, 3, 102, 71, 62, 87, -58, -116, 33, 103, 18, -38, 38, 30, 47, 100, -7, 54, 18, 98, 9, -10, -99, -117, 91, 72, -42, -89, -90, 62, 24, 109, -76, -123, 114, 25, 8, -63, 0, -65, -89, 3, 63, -85, 11, -121, -67, -70, -93, 50, 46, -107, -109, 100, -70, -35, 18, 30, 111, -29, -53, 3, 6, -109, -57, 1, -10, -21, 
  -4, 90, 6, -59, -20, -39, 36, -16, 86, 81, -97, 94, 82, -1, -2, -49, -3, -100, -64, 32, -45, -109, 94, -94, -8, 3, -77, -50, 42, 95, -83, 18, 101, -74, 10, 41, -109, 26, 7, -15, -78, -83, 31, 67, 1, -97, -111, 32, -11, 4, 31, 55, -101, 41, 55, -61, 63, -100, -80, 100, -92, 80, -88, 42, -90, -13, -19, -81, -86, -71, -114, 79, -35, -17, -26, 40, -100, -117, -104, -53, 92, -8, -3, -101, -24, 43, 105, -13, 35, 1, -111, 19, -81, -26, 35, -98, -79, -84, 119, -71, -37, 91, 81, -92, -21, 75, -113, -84, -9, 71, 119, 89, -101, -75, 53, 15, -11, -67, -54, -9, 118, 17, 51, -60, 34, 78, -107, 0, -62, 1, -85, 2, 95, 67, 14, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,135 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0016373754478991032, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<1, float> quant7_scale = { 1, { 5.473597526550293, } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<1, float> quant8_scale = { 1, { 2.7842297554016113, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,3 } };
const TfArray<1, float> quant9_scale = { 1, { 2.7977538108825684, } };
const TfArray<1, int> quant9_zero = { 1, { 127 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant0_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 135, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 12, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 30, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 2700, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 144), (TfLiteIntArray*)&g0::tensor_dimension7, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_1111742_8_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1111742_8_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1111742_8_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1111742_8_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1111742_8_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
